### ISSUE TITLE
請問3通道的圖像可以用嗎？

### ISSUE THREAD

**Issue by Jimmy-Sung** [JustinTebbe/Dynamic-noise-AD#7]
原先MVtec都是4通道的，
使用3通道後一直報錯，
請問作者測試3通道的圖像時可以用嗎？

**Comment by JustinTebbe** [comment]
It should work with 3 channels. As far as I know MVTec also has 3 channels and should work as is with this repo.

I just tested it with the cable category and the good image nr 169:
`from PIL import Image
import numpy as np


img = Image.open("169.png")


print(f"size: {np.array(img).shape}")`
Shows me 3 channels.

Please note that the imput_channel: 4 from the config.yaml file refers to the channel dimension in latent space. As we are making use of the stable diffusion VAE which projects from 3,256,256 to 4,32,32.

**Comment by Jimmy-Sung** [comment]
There are three and four channels in my dataset. I can't make them all match the same number of channels. The following is the error message.

![螢幕擷取畫面 2024-09-11 232345](https://github.com/user-attachments/assets/da9f8c55-9f57-4e71-b29f-af55dfd11a73)

(D3AD) jimmy@DESKTOP-S45S651:/mnt/d/python_code/D3AD$ python main.py
/home/jimmy/miniconda3/envs/D3AD/lib/python3.10/site-packages/kornia/feature/lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
Num params:  281088004
Current device is cuda
/home/jimmy/miniconda3/envs/D3AD/lib/python3.10/site-packages/torch/utils/data/dataloader.py:557: UserWarning: This DataLoader will create 30 worker processes in total. Our suggested max number of worker in current system is 12, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
Epoch 0 | Loss: 0.9952625632286072
Traceback (most recent call last):
  File "/mnt/d/python_code/D3AD/main.py", line 158, in <module>
    execute_main_test()
  File "/mnt/d/python_code/D3AD/main.py", line 154, in execute_main_test
    train(args)
  File "/mnt/d/python_code/D3AD/main.py", line 74, in train
    trainer(unet, constants_dict, ema_helper, config)
  File "/mnt/d/python_code/D3AD/train.py", line 55, in trainer
    for step, batch in enumerate(trainloader):
  File "/home/jimmy/miniconda3/envs/D3AD/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/home/jimmy/miniconda3/envs/D3AD/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1324, in _next_data
    return self._process_data(data)
  File "/home/jimmy/miniconda3/envs/D3AD/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1370, in _process_data
    data.reraise()
  File "/home/jimmy/miniconda3/envs/D3AD/lib/python3.10/site-packages/torch/_utils.py", line 706, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 23.
Original Traceback (most recent call last):
  File "/home/jimmy/miniconda3/envs/D3AD/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 309, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/home/jimmy/miniconda3/envs/D3AD/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 55, in fetch
    return self.collate_fn(data)
  File "/home/jimmy/miniconda3/envs/D3AD/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 317, in default_collate
    return collate(batch, collate_fn_map=default_collate_fn_map)
  File "/home/jimmy/miniconda3/envs/D3AD/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 174, in collate
    return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
  File "/home/jimmy/miniconda3/envs/D3AD/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 174, in <listcomp>
    return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
  File "/home/jimmy/miniconda3/envs/D3AD/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 142, in collate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
  File "/home/jimmy/miniconda3/envs/D3AD/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 214, in collate_tensor_fn
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [3, 256, 256] at entry 0 and [4, 256, 256] at entry 4

**Comment by JustinTebbe** [comment]
Unfortunately, you are dealing with two distinct problems here:

1. The SD VAE takes as input only a 3 channel image. It won't work with 4 channels. You could switch it with a different VAE that supports 4 channels as input or train one yourself.
2. The mix of 3- and 4-channel images in your dataset could be problematic, as most (if not all) VAEs typically support only one fixed channel size. Therefore, you would need to address the channel discrepancy during a preprocessing step. Does the 4th channel contain any meaningful information? If not, you could drop it. If it does, for instance, contain transparency data, why is it missing from the other data points? If it’s missing because there are no overlapping parts and, therefore, no transparency is needed, you could add a 4th channel with zero transparency. However, this solution depends heavily on the specific characteristics of your data.
